### ISSUE TITLE
installing process

### ISSUE THREAD

**Issue by ricou84** [elliotkillick/qubes-video-companion#28]
Hello.
Thank you to contributor this feature look fantastic.

I'm just a newbie with qubes OS. i would like the screen sharing functionality. 

I try this to install : 
`sudo qubes-dom0-update qubes-video-companion`

but it indicates a no match. 

i think there is somthing i did not understand in installation process. is someone can light me?

**Comment by techge** [comment]
As said in [README.md](https://github.com/elliotkillick/qubes-video-companion#installation) this package is WIP, currently you need to build the package yourself, the install instructions you tried are for a future readily-built version.

**Comment by ricou84** [comment]
ok so i close this issue.

hope the integration will be soon
