### ISSUE TITLE
PGP verification issue

### ISSUE THREAD

**Issue by pietrushnic** [elliotkillick/qubes-video-companion#5]
Hi @elliotkillick,
to do `git verify-tag v1.0.4` I need your public key, where I can get and where I can confirm your fingerprint?

Your Github says:

```
Open/libre technology advocate, avid developer, infosec aficionado, student & cybersecurity TA @ UofT SCS. PGP: 018F B9DE 6DFA 13FB 18FB 5552 F9B9 0D44 F83D D5
```

but

```
debian@debian:~/qubes/qubes-video-companion$ git verify-tag v1.0.4
gpg: Signature made Wed 21 Apr 2021 07:34:10 AM CEST
gpg:                using EDDSA key 018FB9DE6DFA13FB18FB5552F9B90D44F83DD5F2
gpg: Can't check signature: No public key
```

It looks like you missing `F2` at the end.

**Comment by elliotkillick** [comment]
Whoops, looks like I hit the character limit on my GitHub bio and accidentally truncated a couple characters off the end of my PGP signature. That is indeed my correct signature and this issue has now been fixed.

If you want to get my PGP signature so it says "Good signature" then also run this before `git verify-tag`:
`gpg --keyserver keys.openpgp.org --recv-keys 018FB9DE6DFA13FB18FB5552F9B90D44F83DD5F2`
