### ISSUE TITLE
Building deb pkg fails

### ISSUE THREAD

**Issue by pietrushnic** [elliotkillick/qubes-video-companion#6]
I'm probably doing something wrong:

```
$ dpkg-source --before-build .
$ dpkg-buildpackage -us -uc   
dpkg-buildpackage: info: source package qubes-video-companion
dpkg-buildpackage: info: source version 1.0.0-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Elliot Killick <elliotkillick@zohomail.eu>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 fakeroot debian/rules clean
dh clean
   dh_auto_clean
        make -j8 clean
make[1]: Entering directory '/home/user/src/qubes/qubes-video-companion'
make -C doc clean
make[2]: Entering directory '/home/user/src/qubes/qubes-video-companion/doc'
rm -f qubes-video-companion.1.gz
make[2]: Leaving directory '/home/user/src/qubes/qubes-video-companion/doc'
make[1]: Leaving directory '/home/user/src/qubes/qubes-video-companion'
   dh_clean
 dpkg-source -b .
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../qubes-video-companion_1.0.0.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 255
```

Where is the source for `qubes-video-companion`, if any?

**Comment by elliotkillick** [comment]
To build a Debian package you must first create at tarball of it one directory up from where the cloned repo itself is located. This is standard procedure for building any Debian package not a bug in this project.

Please look up a guide on how to build Debian packages.

**Comment by pietrushnic** [comment]
If project seeking for support from community then README and associated documentation for testing should be robust, even if it points to external resources. There are too many assumptions about tester knowledge to attract casual testers.

This small thing stopped me from continue testing this for more then month.

**Comment by elliotkillick** [comment]
100% agree, I actually intended on creating a script that would install all the necessary development packages and build the package for you. However, I was very busy at the time and then it slipped out of my mind.

I appreciate you taking the time to try and test despite insufficient support from me.
