### ISSUE TITLE
v4l2sink missing?

### ISSUE THREAD

**Issue by 0spinboson** [elliotkillick/qubes-video-companion#7]
![image](https://user-images.githubusercontent.com/21077532/115773630-10fc5800-a3a0-11eb-8658-8a7ac9e5a94a.png)

Thank you for your work, looks very neat. :) Wanted to help test it. 

First had to install qv4l2, v4l-utils, gstreamer1-plugins-base-devel, (gstreamer1-plugins-good). (Please add this to documentation?)
Installed those in AppVM and sys-usb, now I get this. Not sure what it's about, because afaict v4l2sink is provided by plugins-good?

**Comment by elliotkillick** [comment]
Yes, `v4l2sink` should be included in the `gstreamer1-plugins-good` package.

Please confirm that you have it with:
`gst-inspect-1.0 v4l2sink`

Also, you have to install AppIndicator for the UI to work (`libappindicator-gtk3` package in Fedora). I recommend just building the RPM/DEB for it will handle all the package dependencies for you. Please look up a guide on how to do that, it's quite simple.

**Comment by 0spinboson** [comment]
okay. Guess I'll wait until it's in the repo, then, I seem to be too stupid to get it to work, myself. Thank you. :)
